import { govPoolABI } from '../abi';

export const bscStakePools = [
  {
    id: 'coink-bnb',
    name: 'COINK',
    logo: 'single-assets/COINK.png',
    token: 'COINK',
    tokenDecimals: 18,
    tokenAddress: '0xCa3F508B8e4Dd382eE878A314789373D80A5190A',
    tokenOracle: 'tokens',
    tokenOracleId: 'COINK',
    earnedToken: 'BNB',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    earnContractAddress: '0x453D4Ba9a2D594314DF88564248497F7D74d6b2C',
    earnContractAbi: govPoolABI,
    earnedOracle: 'tokens',
    earnedOracleId: 'WBNB',
    partnership: false,
    status: 'active',
    hideCountdown: true,
    partners: [
      {
        logo: 'stake/piggybank/piggybankfinance.png',
        logoNight: 'stake/piggybank/piggybankfinance_night.png',
        background: 'stake/piggybank/background.png',
        text: "You probably already knew that Piggybank Vault is the most trusted Yield optimizer for the Binance Smart Chain. But did you know that Piggybank has its own token? COINK has a maximum supply of 80000 tokens and there is no way to mint more. Everyone who holds our own COINK token can not only do cool stuff like create and vote on proposals, they also get a share of all harvests done, every hour, every day on all our +120 vaults. That's a lot of BNB that goes straight to our COINK holders. All you have to do is stake your COINK in this vault, it’s that simple, come back and harvest your BNB whenever you need it! (You can still vote on proposals even though you have staked your COINK here).",
        website: 'https://vault.piggybankone.finance',
        social: {
          telegram: 'http://t.me/piggybankonevault',
          twitter: 'https://twitter.com/piggybankonevault',
        },
      },
    ],
  },
  {
    id: 'pig_cake-cakev2',
    name: 'Piggybank Vault',
    logo: 'single-assets/CAKE.svg',
    token: 'pigCakeV2',
    tokenDecimals: 18,
    tokenAddress: '0x97e5d50Fe0632A95b9cf1853E744E02f7D816677',
    tokenOracle: 'tokens',
    tokenOracleId: 'Cake',
    earnedToken: 'pigCOINK',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0xf7069e41C57EcC5F122093811d8c75bdB5f7c14e',
    earnContractAddress: '0xA17A86e836199489801A00B50b9C09525ddC232b',
    earnContractAbi: govPoolABI,
    earnedOracle: 'tokens',
    earnedOracleId: 'COINK',
    partnership: true,
    status: 'active',
    isPigStaked: true,
    periodFinish: 1625930588,
    partners: [
      {
        logo: 'stake/piggybank/piggybankfinance.png',
        logoNight: 'stake/piggybank/piggybankfinance_night.png',
        background: 'stake/piggybank/background.png',
        text: 'Piggybank Finance Vault is the Multichain Yield Optimizer that allows its users to earn compound interest on their holdings. A yield optimizer is an automated service that seeks to gain the maximum possible return on crypto-investments made through DeFi platforms. This is much more efficient than attempting to maximize your returns by doing everything manually. It also means you don’t have to sit in front of a screen all day. So Piggybank Finance Vault is a platform that puts your crypto to work for maximum ROI with minimum effort. COINK is the governance token of the Piggybank Finance Vault platform. This means that when you own some COINK, you get the right to create and vote on proposals to do with the future of the platform. Third, the fun part: COINK tokens can be staked on Piggybank Vault to earn a share of the revenue created by the Piggybank Vault platform.',
        website: 'https://vault.piggybankone.finance',
        social: {
          telegram: 'http://t.me/piggybankonevault',
          twitter: 'https://twitter.com/piggybankonevault',
        },
      },
    ],
  },
];
